// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YazOkulu.Data.Context;

#nullable disable

namespace YazOkulu.Data.Migrations
{
    [DbContext(typeof(YazOkuluDbContext))]
    [Migration("20251121171130_currentQuatoAdded")]
    partial class currentQuatoAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YazOkulu.Data.Models.Application", b =>
                {
                    b.Property<int>("ApplicationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("application_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationID"));

                    b.Property<int>("CourseID")
                        .HasColumnType("int")
                        .HasColumnName("course_id");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("create_date");

                    b.Property<int?>("CreateUserID")
                        .HasColumnType("int")
                        .HasColumnName("create_user_id");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("delete_date");

                    b.Property<int?>("DeleteUserID")
                        .HasColumnType("int")
                        .HasColumnName("delete_user_id");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("guid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("modify_date");

                    b.Property<int?>("ModifyUserID")
                        .HasColumnType("int")
                        .HasColumnName("modify_user_id");

                    b.Property<int>("StatusID")
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    b.Property<int>("UserID")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("ApplicationID")
                        .HasName("pk_applications");

                    b.HasIndex("CourseID")
                        .HasDatabaseName("i_x_applications_course_id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("i_x_applications_is_deleted");

                    b.HasIndex("StatusID")
                        .HasDatabaseName("i_x_applications_status_id");

                    b.HasIndex("UserID")
                        .HasDatabaseName("i_x_applications_user_id");

                    b.ToTable("applications");
                });

            modelBuilder.Entity("YazOkulu.Data.Models.Course", b =>
                {
                    b.Property<int>("CourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("course_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseID"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("code");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("create_date");

                    b.Property<int?>("CreateUserID")
                        .HasColumnType("int")
                        .HasColumnName("create_user_id");

                    b.Property<int?>("CurrentQuota")
                        .HasColumnType("int")
                        .HasColumnName("current_quota");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("delete_date");

                    b.Property<int?>("DeleteUserID")
                        .HasColumnType("int")
                        .HasColumnName("delete_user_id");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int")
                        .HasColumnName("department_id");

                    b.Property<int>("FacultyID")
                        .HasColumnType("int")
                        .HasColumnName("faculty_id");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("guid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("modify_date");

                    b.Property<int?>("ModifyUserID")
                        .HasColumnType("int")
                        .HasColumnName("modify_user_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int>("Quota")
                        .HasColumnType("int")
                        .HasColumnName("quota");

                    b.HasKey("CourseID")
                        .HasName("p_k__courses");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("i_x_courses_is_deleted");

                    b.ToTable("courses");
                });

            modelBuilder.Entity("YazOkulu.Data.Models.GsmOtp", b =>
                {
                    b.Property<int>("GsmOtpID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("gsm_otp_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GsmOtpID"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("create_date");

                    b.Property<int?>("CreateUserID")
                        .HasColumnType("int")
                        .HasColumnName("create_user_id");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("delete_date");

                    b.Property<int?>("DeleteUserID")
                        .HasColumnType("int")
                        .HasColumnName("delete_user_id");

                    b.Property<string>("Gsm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("gsm");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("guid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("modify_date");

                    b.Property<int?>("ModifyUserID")
                        .HasColumnType("int")
                        .HasColumnName("modify_user_id");

                    b.Property<string>("Otp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("otp");

                    b.HasKey("GsmOtpID")
                        .HasName("pk_gsm_otps");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("i_x_gsm_otps_is_deleted");

                    b.ToTable("gsm_otps");
                });

            modelBuilder.Entity("YazOkulu.Data.Models.Parameter", b =>
                {
                    b.Property<int>("ParameterID")
                        .HasColumnType("int")
                        .HasColumnName("parameter_id");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("create_date");

                    b.Property<int?>("CreateUserID")
                        .HasColumnType("int")
                        .HasColumnName("create_user_id");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("delete_date");

                    b.Property<int?>("DeleteUserID")
                        .HasColumnType("int")
                        .HasColumnName("delete_user_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("guid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("modify_date");

                    b.Property<int?>("ModifyUserID")
                        .HasColumnType("int")
                        .HasColumnName("modify_user_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentParameterID")
                        .HasColumnType("int")
                        .HasColumnName("parent_parameter_id");

                    b.HasKey("ParameterID")
                        .HasName("p_k__parameters");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("i_x_parameters_is_deleted");

                    b.ToTable("parameters");
                });

            modelBuilder.Entity("YazOkulu.Data.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("create_date");

                    b.Property<int?>("CreateUserID")
                        .HasColumnType("int")
                        .HasColumnName("create_user_id");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("delete_date");

                    b.Property<int?>("DeleteUserID")
                        .HasColumnType("int")
                        .HasColumnName("delete_user_id");

                    b.Property<int?>("DepartmentTypeID")
                        .HasColumnType("int")
                        .HasColumnName("department_type_id");

                    b.Property<int?>("FacultyTypeID")
                        .HasColumnType("int")
                        .HasColumnName("faculty_type_id");

                    b.Property<string>("Gsm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("gsm");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("guid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("modify_date");

                    b.Property<int?>("ModifyUserID")
                        .HasColumnType("int")
                        .HasColumnName("modify_user_id");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<int>("RoleTypeID")
                        .HasColumnType("int")
                        .HasColumnName("role_type_id");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_name");

                    b.HasKey("UserID")
                        .HasName("p_k__users");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("i_x_users_is_deleted");

                    b.ToTable("users");
                });

            modelBuilder.Entity("YazOkulu.Data.Models.Application", b =>
                {
                    b.HasOne("YazOkulu.Data.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YazOkulu.Data.Models.Parameter", "StatusType")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YazOkulu.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("StatusType");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
